/*
 * (c) 2025, Infineon Technologies AG, or an affiliate of Infineon
 * Technologies AG. All rights reserved.
 * This software, associated documentation and materials ("Software") is
 * owned by Infineon Technologies AG or one of its affiliates ("Infineon")
 * and is protected by and subject to worldwide patent protection, worldwide
 * copyright laws, and international treaty provisions. Therefore, you may use
 * this Software only as provided in the license agreement accompanying the
 * software package from which you obtained this Software. If no license
 * agreement applies, then any use, reproduction, modification, translation, or
 * compilation of this Software is prohibited without the express written
 * permission of Infineon.
 * 
 * Disclaimer: UNLESS OTHERWISE EXPRESSLY AGREED WITH INFINEON, THIS SOFTWARE
 * IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING, BUT NOT LIMITED TO, ALL WARRANTIES OF NON-INFRINGEMENT OF
 * THIRD-PARTY RIGHTS AND IMPLIED WARRANTIES SUCH AS WARRANTIES OF FITNESS FOR A
 * SPECIFIC USE/PURPOSE OR MERCHANTABILITY.
 * Infineon reserves the right to make changes to the Software without notice.
 * You are responsible for properly designing, programming, and testing the
 * functionality and safety of your intended application of the Software, as
 * well as complying with any legal requirements related to its use. Infineon
 * does not guarantee that the Software will be free from intrusion, data theft
 * or loss, or other breaches ("Security Breaches"), and Infineon shall have
 * no liability arising out of any Security Breaches. Unless otherwise
 * explicitly approved by Infineon, the Software may not be used in any
 * application where a failure of the Product or any consequences of the use
 * thereof can reasonably be expected to result in personal injury.
 */

/**
* @file cy_lpa_wifi_ol.h
* @brief Offload API called by Offload Manager.
*/

#ifndef OL_H__
#define OL_H__  (1)

#ifdef __cplusplus
extern "C" {
#endif

typedef struct ol_fns ol_fns_t;

/*******************************************************************************
* LPA Data Structures
*******************************************************************************/

/******************************************************************************/
/** \addtogroup group_lpa_structures *//** \{ */
/******************************************************************************/

/** Offload instance description table entry.
 * Defines a specific instance and configuration for an offload.
 * This entry may be automatically generated by a software configurator.
 * A table of entries made available to the Offload Manager. */
typedef struct ol_desc
{
    const char *name;           /**< Friendly name for debug (XXX: make debug only). */
    const void *cfg;            /**< Offload-specific configuration. */
    const struct ol_fns *fns;   /**< Offload-specific function pointers (extern'd by offloads). */
    void *ol;                   /**< Offload-specific instance (context) pointer. */
    void *worker_thread;        /**< Worker Thread used by Offload Manager. */
} ol_desc_t;

/** \} */

#ifdef __cplusplus
}
#endif

#endif /* !OL_H__ */

